services:
  app-first:
    build: .
    restart: always
    ports:
      - '8080:8080'
    environment:
      MONGODB_URL: mongodb://mongo:27017/mgt-1
      URL: http://151.248.113.166:8080
    depends_on:
      - mongo

  app-second:
    build: .
    restart: always
    ports:
      - '8081:8080'
    environment:
      MONGODB_URL: mongodb://mongo:27017/mgt-2
      URL: http://151.248.113.166:8081
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
